### ISSUE TITLE
Feedback on reproducibility

### ISSUE THREAD

**Issue by Duniie** [DorienHuijser/cd2-survey#1]
**1. What project did you reproduce (include the link)?**

->  [cd2-survey](https://github.com/DorienHuijser/cd2-survey)

**2. Does the project have the following on it's GitHub repository?**

- [X] README
- [X] A license
- [ ] Citation information
- [X] Requirements for running the code (dependencies)
- [X] An understandable folder structure

**3. What did you appreciate about the project's repository?**

-> The READMe and dependencies file is very nicely explained. I really liked the structure of the repository

**4. Do you have any suggestions for improvement to the repository?**

-> I think the data and code files were a little bit confusing and not very intuitive, so it took me some time to find where the data was

**5. Did you manage to run the project successfully?**

- [ ] Yes
- [ ] Largely
- [X] No
- [ ] Other (please specify):

**6. Where did you have to give up reproducing this repository (if applicable)?**

-> The file that the repository was calling for was not included in the project

**7. Did you have to go into the code?**

- [X] Yes
- [ ] No
- [ ] I didn't have to, but I had time left/was intrigued, so I did it anyway!

**8. If you looked at the code: what did you like?**

-> It has a good and easy to read structure, I also really like how organised the repository files are

**9. If you looked at the code, what would be a single line of advice you want to pass on to it's author?**

-> I used to work with a lot of for loops, but now I am working a little bit more with dplyr pipes %>%. May be an idea to learn this other technique. it shortens the code considerably

**10. Any final comments to the author?**

-> You have put a lot of effort into writing a good repository. You just need to double check the reproducibility of the code

**11. Do you think the class will benefit from a live demo of the reproduction of this project? Why/what can we learn?**

-> I think showing the README and dependencies files and how you structured the repository would be beneficial

**Comment by DorienHuijser** [comment]
Agreed, I will make more clear where the files are located. And indeed I want to work on the readability and length of the script, because it is extremely long and inefficient at the moment, but this is mostly due to my novice programming skills ;) Thanks for your feedback!

FYI: Citation information is included, just not in the README file, I will add it there as well.
